---
title: "HLP_Responses"
author: "Surya Dhulipala"
date: "3/2/2022"
output: html_document
---

```{r}
# Set the working directory to current directory 
#----------------- You will need to change this if you are using Microsoft ------------------
setwd("~/Sync/iREACH/Students/Surya/Rogers Presentations/20220301/Overlaying_HLP_AQHI_Datasets")

# This section is for installing libraries

# Package names
packages <- c("ggplot2", "plyr","dplyr","tidyr", "latticeExtra", "data.table", "openair", "readr", "reshape2", "corrplot", "ggiraph","ggiraphExtra", "ggpubr", "ggpmisc","caret","factoextra", "ggfortify","gridExtra", "ggbiplot", "openair", "lubridate","car", "reshape2","rmarkdown", "gtools","caret","purrr","tidyr","kableExtra","tidyverse","captioner","lubridate","latticeExtra",
              "worldmet")


# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages], repos = "http://cran.us.r-project.org")
  
  library(devtools)
install_github("vqv/ggbiplot")
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

```

```{r}

HLP_Responses <- read.csv(file = "HLP_Responses.csv")

# Choose just the last column of dates
HLP_Frequency_Responses <- HLP_Responses$Created.at

# Convert the date into PDT
HLP_Frequency_Responses <- as.Date(as.POSIXct(HLP_Frequency_Responses, 
                            tz = "America/Vancouver", 
                            format = "%Y-%m-%d"))

## Tabulate
tab <- table(cut(HLP_Frequency_Responses, 'day'))

## Format
HLP_Responses <- data.frame(date=format(as.Date(names(tab)), '%Y-%m-%d'),
           Frequency=as.vector(tab))
HLP_Responses$date <- as.Date(HLP_Responses$date, '%Y-%m-%d')

```

```{r}
# Reading the calibrated air quality file
campusaq <- read.csv(file = "campusaq.csv")

# Convert the date-time into PDT
campusaq$date <- as.POSIXct(campusaq$date, 
                            tz = "America/Vancouver")

# Provide an end date time for subsetting the date column (we have ~4.5 months of Raw Data from Hello Lamp Post)
enddatetime <- '2021-10-07 00:00'
enddatetime <- as.POSIXct(enddatetime, tz = "America/Vancouver")

# Only choosing the Wesbrook Mall and University Blvd sensor
campusaq <- campusaq[ which(campusaq$RAMP_IDs=='1085' & campusaq$date <= enddatetime), ]

# Hourly average
campusaq_hourly <- timeAverage(campusaq,"hour")

```




```{r}
# Determining the AQHI 
All_Hourly <- campusaq_hourly

#For AQHI Calculations. First calculate 3 hour rolling mean
All_Hourly <- rollingMean(All_Hourly,pollutant=c("NO2_RAMP"),width = 3)
All_Hourly <- rollingMean(All_Hourly,pollutant="O3_RAMP",width = 3)
All_Hourly <- rollingMean(All_Hourly,pollutant="PM_RAMP",width = 3)
All_Hourly <- rollingMean(All_Hourly,pollutant="PM_RAMP",width = 1)

All_Hourly <- All_Hourly %>%
  mutate(AQHI=10/10.4*(100*(exp(0.000871*rolling3NO2_RAMP)-1+exp(0.000537*rolling3O3_RAMP)-1+exp(0.000487*rolling3PM_RAMP)-1)))%>%
  mutate(AQHI_plus = ifelse(rolling1PM_RAMP>100, 10, ceiling(rolling1PM_RAMP/10))) %>%
  mutate(max_AQHI = pmax(AQHI, AQHI_plus))
All_Hourly <- na.omit(All_Hourly)


All_Daily <- timeAverage(All_Hourly, "day")

# Convert the date-time into PDT
All_Daily$date <- as.POSIXct(All_Daily$date, tz = "America/Vancouver")
All_Daily$date <- as.Date(All_Daily$date, format = '%Y-%m-%d')
All_Daily <- All_Daily %>% inner_join(HLP_Responses,by="date")

# AFter the inner join, R is not recognizing the date format, so I am providing that again 
All_Daily$date <- as.POSIXct(All_Daily$date,format="%Y-%m-%d",tz=Sys.timezone())


```

```{r}
# Plots the overlaid plot of AQHI and community responses

# Change this coefficient if you want to change the scaling for right y-axis. Scaling of right y axis is raltive to the left y-axis. Coeff is the multiplier. 
Coeff <- 1

# Need to provide the labels from low risk to high risk
All_Daily_1 <- All_Daily %>%
  mutate(color = cut(max_AQHI,c(1,2,3,4,5,6,7,8,9,10,Inf),
                     
                     labels = c("1 (Low Risk)","2 (Low Risk)","3 (Low Risk)","4 (Moderate Risk)","5 (Moderate Risk)","6 (Moderate Risk)","7 (High Risk)","8 (High Risk)","9 (High Risk)","10+ (Very High Risk)"))) %>%
  
  
  # ggplot stuff
  ggplot(aes(x = date, y = PM_RAMP, color = color, group = 1)) +
  
    geom_col(aes(x = date, y = Frequency*Coeff),
           size = 0.5,
           color = "black",
           fill = "white") +
  
  geom_line(size = 1.5)+
  
 scale_color_manual(values = c("deepskyblue1", "dodgerblue", "dodgerblue4", "yellow", "gold", "goldenrod", "lightcoral","red", "red3", "red4"), drop =FALSE) + 
  
  labs(colour = "AQHI Value") + 
  
  labs (x = "Date", y = bquote('PM'[2.5]~'('*µg~m^-3*')'), 
        
        title = bquote("Air Quality Health Index vs" ~ PM[2.5]~ " vs Community Responses")) + 
  
  theme(axis.title.x = element_text(margin = margin(t = 10))) + 
  
  scale_x_datetime(labels = scales::date_format("%b %d", tz = "America/Los_Angeles"))+
  
  # Custom Y scaling:
  scale_y_continuous(

    # Features of the first axis
    name = "Community Responses Per Day",

    # Add a second axis and specify its features
    sec.axis = sec_axis( trans=~.*Coeff,
                         name= bquote('Daily Averaged PM'[2.5]~'('*µg~m^-3*')'~''),)) +
    # Change the fint size of graph elements
    theme(axis.title.x = element_text(margin = margin(t = 16))) +
    theme(axis.title = element_text(size = 16))   +
    theme(plot.title = element_text(size = 16)) 
    

print(All_Daily_1)

```

```{r}

# If you only want to plot the community responses per day

    ggplot(All_Daily) +
    geom_col(aes(x = date, y = Frequency),
           size = 0.5,
           color = "black",
           fill = "white")+ 
  
    theme(axis.title.x = element_text(margin = margin(t = 16))) +
    theme(axis.title = element_text(size = 16))   +
    theme(plot.title = element_text(size = 16)) 


```